apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  ports:
  - port: 8000
    name: http
  selector:
    app: auth-service
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
      version: v1
  template:
    metadata:
      labels:
        app: auth-service
        version: v1
      name: auth-service
    spec:
      containers:
        - name: auth-service
          image: filhoeduardo83/auth-service:1.0
          ports:
            - containerPort: 8000
          env:
            - name: APPLICATION_ENVIRONMENT
              value: prod
            - name: APPLICATION_PORT
              value: "8000"
            - name: JDBC_DATABASE_URL
              value: jdbc:postgresql://auth-postgres:5432/postgres
            - name: JDBC_DATABASE_USERNAME
              value: postgres
            - name: JDBC_DATABASE_PASSWORD
              value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-port
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30008
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-postgres
spec:
  selector:
    matchLabels:
      app: auth-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-postgres
    spec:
      volumes:
        - name: postgres-auth-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
      - name: auth-postgres
        image: filhoeduardo83/login-postgres:1.0
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-auth-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres-auth
---
apiVersion: v1
kind: Service
metadata:
  name: auth-postgres
spec:
  type: ClusterIP
  selector:
    app: auth-postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: auth-postgres-port
spec:
  type: NodePort
  selector:
    app: auth-postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30058


